apiVersion: v1
kind: Pod
metadata:
  name: web-app-pod
  labels:
    app.kubernetes.io/name: webapp
spec:
  containers:
    - name: my-web-app
      image: 690612321301.dkr.ecr.us-east-1.amazonaws.com/web-application-image-repo:v2.0
      ports:
        - containerPort: 8080
      env:
        - name: DBHOST
          value: "10.244.0.5"
        - name: DBPORT
          value: "3306"
        - name: DBPWD
          value: "vedha.123"
