apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-container
  namespace: final
  labels:
    app: employees
    version: v1
    app.kubernetes.io/name: webapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: employees
      version: v1
      app.kubernetes.io/name: webapp
  template:
    metadata:
      labels:
        app: employees
        version: v1
        app.kubernetes.io/name: webapp
    spec:
      containers:
        - name: app-container
          image: 690612321301.dkr.ecr.us-east-1.amazonaws.com/clo835_final_project_app:v1.0
          ports:
            - containerPort: 8080
          env:
            - name: DBHOST
              value: "mysql-service.final.svc.cluster.local"
            - name: DBPORT
              value: "3306"
            - name: DBUSER
              valueFrom:
                secretKeyRef:
                  name: mysql-credentials
                  key: DBUSER
            - name: DBPWD
              valueFrom:
                secretKeyRef:
                  name: mysql-credentials
                  key: DBPWD
            - name: DATABASE
              value: employees
            - name: APP_COLOR
              value: blue
            - name: YOUR_NAME
              valueFrom:
                configMapKeyRef:
                  name: webapp-configmap
                  key: YOUR_NAME  # Use the correct key here
            - name: BACKGROUND_IMAGE_URL
              valueFrom:
                configMapKeyRef:
                  name: webapp-configmap
                  key: BACKGROUND_IMAGE_URL
      imagePullSecrets:
        - name: regcred
