apiVersion: v1
kind: Service
metadata:
  name: app-container-service
  namespace: webapp
spec:
  ports:
    - name: http
      protocol: TCP
      port: 81
      targetPort: 81
      nodePort: 30000
  selector:
    app: employees
    version: v1
  type: NodePort
