apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: webapp-replica
  namespace: final
  labels:
    app: employees
    version: v1
spec:
  replicas: 3
  selector:
    matchLabels:
        app: employees
        version: v1
  template:
    metadata:
      labels:
          app: employees
          version: v1
    spec:
      containers:
      - image: 209830628404.dkr.ecr.us-east-1.amazonaws.com/finalexam-app:1.0
        name: webapp-pod
        ports:
        - containerPort: 8080
        env:
        - name: DBHOST
          value: "10.244.0.13"
        - name: DBPORT
          value: "3306"
        - name: DBPWD
          value: "vedha.123"