apiVersion: v1
kind: Pod
metadata:
  name: web-app-pod
  namespace: final
  labels:
    app.kubernetes.io/name: webapp
spec:
  containers:
    - name: my-web-app
      image: 209830628404.dkr.ecr.us-east-1.amazonaws.com/finalexam-app:1.0
      ports:
        - containerPort: 8080
      envFrom:
        - configMapRef:
            name: web-app-configmap
  restartPolicy: Never
